project:
  type: book
  output-dir: _output
book:
  title: "RUG PhD Thesis Template"
  subtitle: "A template for writing a PhD thesis in Quarto"
  author: "Gabriele Sarti"
  date: today
  date-format: "MMM Do, YYYY"
  output-file: "thesis"
  chapters:
    - index.qmd
    - part: "Part Alpha"
      chapters:
        - chapters/intro.qmd
    - part: "Part Beta"
      chapters:
        - chapters/summary.qmd
    - references.qmd
  appendices: 
    - chapters/appendices/appendix-a.qmd

lang: "nld"
frontmatter:
  # Details page
  department: "Center for Language and Cognition Groningen (CLCG)"
  faculty: "Faculty of Arts"
  funding_agency: "Dutch Research Council (NWO)" # Leave empty if not applicable
  funding_project_type: "NWA-ORC"
  funding_project_title: "InDeep: Interpreting Deep Learning Models for Text and Sound"
  funding_project_number: "NWA.1292.19.399"
  document_formatting_comment: "Document prepared with Quarto and typeset using pdfLatex"
  cover_designer: "Gabriele Sarti"
  book_series: "Groningen Dissertations in Linguistics"
  volume: "XXX"
  year: "2025"

  # Front matter
  
  eng:
    document_type: "PhD Thesis"
    degree: "PhD"
    university: "University of Groningen"
    rector_magnificus: "Prof. J. M. A. Scherpen"
    defense_date: "XXX, XXX XXX 2025" # Use e.g. Thursday, June 13th 2024 format
    candidate_birth_date: "DD mmmm YYYY" # Use e.g. 22 January 1996
  nld:
    document_type: "Proefschrift"
    degree: "doctor"
    university: "Rijksuniversiteit Groningen"
    rector_magnificus: "prof. dr. ir. J. M. A. Scherpen"
    defense_date: "XXX, XXX XXX 2025" # Use e.g. donderdag 16 november 2023 format
    candidate_birth_date: "DD mmmm YYYY" # Use e.g. 4 februari 1994
  defense_time: "XX:XX"
  candidate_birthplace: "Amsterdam, the Netherlands"



  # Supervisors and examiners
  promotor_title: "Dr."
  promotor_name: "Arianna Bisazza"
  first_copromotor_title: "Prof. Dr."
  first_copromotor_name: "Malvina Nissim"
  second_copromotor_title: "Dr."
  second_copromotor_name: "Grzegorz Chrupa≈Ça"
  first_assessment_committee_title: "Prof. dr."
  first_assessment_committee_name: "XXX XXX"
  second_assessment_committee_title: "Prof. dr."
  second_assessment_committee_name: "XXX XXX"
  third_assessment_committee_title: "Prof. dr."
  third_assessment_committee_name: "XXX XXX"

  # Front matter


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    template: template/rug-phd-thesis.tex
    pdf-engine: pdflatex
    keep-tex: false


