project:
  type: book
  output-dir: _output
book:
  title: "RUG PhD Thesis Template" # Your thesis title
  subtitle: "" # Your thesis subtitle if present, empty otherwise
  author: "Gabriele Sarti" # Your name in FirstName LastName format
  favicon: figures/logos/rug_crest.png # Icon for the web version of the thesis
  description: A template for writing a RUG PhD thesis in Quarto. # Description for the web version of the thesis
  keyword: phd, thesis, quarto, template, groningen, rug, gronlp # Keywords for the web version of the thesis
  url: https://gsarti.com/phd-thesis # The URL at which your thesis will be published
  sidebar: 
    logo: figures/logos/rug_crest.png # Remove if you don't want any logo in the website sidebar
    logo-alt: RUG Coat of Arms # Remove if you don't want any logo in the website sidebar
    search: true
    background: "#F5F5F5"
    tools:
      - icon: github
        href: https://github.com/gsarti/phd-thesis
      - icon: person-circle
        href: https://gsarti.com
  date: today
  date-format: "MMM Do, YYYY"
  output-file: "thesis"
  chapters:
    - index.qmd
    - chapters/chap-2-background.qmd
    - part: "Context Usage in Machine Translation and Multilingual NLP"
      chapters:
        - chapters/chap-3-inseq.qmd
        - chapters/chap-4-pecore.qmd
        - chapters/chap-5-mirage.qmd
    - part: "Conditioning Generation for Personalized Machine Translation"
      chapters:
        - chapters/chap-6-ramp.qmd
        - chapters/chap-7-sae-litmt.qmd
    - part: "Towards Interpretability in Human Translation Workflows"
      chapters:
        - chapters/chap-8-divemt.qmd
        - chapters/chap-9-unsup-wqe.qmd
        - chapters/chap-10-qe4pe.qmd
    - chapters/references.qmd
  appendices: 
    - chapters/appendix-a.qmd

pdf-lang: "eng"
freeze: auto
frontmatter:

  # Details page
  department: "Center for Language and Cognition Groningen (CLCG)"
  faculty: "Faculty of Arts"
  funding_agency: "Dutch Research Council (NWO)" # Leave empty if not applicable
  funding_project_type: "NWA-ORC"
  funding_project_title: "InDeep: Interpreting Deep Learning Models for Text and Sound"
  funding_project_number: "NWA.1292.19.399"
  document_formatting_comment: "Document prepared with Quarto and typeset using pdfLatex"
  cover_designer: "Gabriele Sarti"
  book_series: "Groningen Dissertations in Linguistics"
  volume: "XXX"
  year: "2025"

  # Front matter
  eng:
    university: "University of Groningen"
    defense_date: "XXX, XXX XXX 2025" # Use e.g. Thursday, June 13th 2024 format
    candidate_birth_date: "November 11th, 1996" # Use e.g. January 22nd, 1996
    rector_magnificus: "Prof. J. M. A. Scherpen"
  nld:
    university: "Rijksuniversiteit Groningen"
    rector_magnificus: "prof. dr. ir. J. M. A. Scherpen"
    defense_date: "XXX, XXX XXX 2025" # Use e.g. donderdag 16 november 2023 format
    candidate_birth_date: "11 november 1996" # Use e.g. 4 februari 1994
  defense_time: "XX:XX"
  candidate_birthplace: "Trieste, Italy"

  # Supervisors and examiners
  supervisors:
    - title: "Dr."
      name: "Arianna Bisazza"
    - title: "Prof. dr."
      name: "Malvina Nissim"
  cosupervisors:
    - title: "Dr."
      name: "Grzegorz Chrupa≈Ça"
  committee:
    - title: "Prof. dr."
      name: "Michael Biehl"
    - title: "Prof. dr."
      name: "Barbara Plank"
    - title: "Prof. dr."
      name: "Andre F. T. Martins"
    - title: "Dr."
      name: "Ivan Titov"
  
  dedication: "" # E.g. "To my dog". Leave empty to skip

bibliography:
- latex/references/anthology-filtered.bib
- latex/references/index.bib
- latex/references/chap-2-background.bib
- latex/references/chap-3-inseq.bib
- latex/references/chap-4-pecore.bib
- latex/references/chap-5-mirage.bib
- latex/references/chap-6-ramp.bib
- latex/references/chap-7-sae-litmt.bib
- latex/references/chap-8-divemt.bib
- latex/references/chap-9-unsup-wqe.bib
- latex/references/chap-10-qe4pe.bib
- latex/references/appendices.bib
bibliographystyle: latex/rug-phd-thesis.bst

format:
  html:
    filters:
      - pdf-to-image
    theme:
      light: cosmo
    code-fold: false
    css: html/custom.css
    backgroundcolor: "#F5F5F5"
    tbl-cap-location: bottom
  pdf:
    filters:
      - at: pre-ast
        path: _extensions/gsarti/rug-phd-thesis/rug-phd-thesis.lua
    template: latex/rug-phd-thesis.tex
    cite-method: natbib
    link-citations: true
    pdf-engine: pdflatex
    keep-tex: true
    fig-pos: "t"
    tbl-cap-location: bottom


