project:
  type: book
  output-dir: _output
book:
  title: "RUG PhD Thesis Template"
  subtitle: "A template for writing a PhD thesis in Quarto"
  author: "Gabriele Sarti"
  date: today
  date-format: "MMM Do, YYYY"
  output-file: "thesis"
  chapters:
    - index.qmd
    - part: "Part Alpha"
      chapters:
        - chapters/intro.qmd
    - part: "Part Beta"
      chapters:
        - chapters/summary.qmd
    - references.qmd
  appendices: 
    - chapters/appendices/appendix-a.qmd

lang: "eng"
frontmatter:
  # Details page
  department: "Center for Language and Cognition Groningen (CLCG)"
  faculty: "Faculty of Arts"
  funding_agency: "Dutch Research Council (NWO)" # Leave empty if not applicable
  funding_project_type: "NWA-ORC"
  funding_project_title: "InDeep: Interpreting Deep Learning Models for Text and Sound"
  funding_project_number: "NWA.1292.19.399"
  document_formatting_comment: "Document prepared with Quarto and typeset using pdfLatex"
  cover_designer: "Gabriele Sarti"
  book_series: "Groningen Dissertations in Linguistics"
  volume: "XXX"
  year: "2025"

  # Front matter
  eng:
    university: "University of Groningen"
    defense_date: "XXX, XXX XXX 2025" # Use e.g. Thursday, June 13th 2024 format
    candidate_birth_date: "November 11th, 1996" # Use e.g. January 22nd, 1996
    rector_magnificus: "Prof. J. M. A. Scherpen"
  nld:
    university: "Rijksuniversiteit Groningen"
    rector_magnificus: "prof. dr. ir. J. M. A. Scherpen"
    defense_date: "XXX, XXX XXX 2025" # Use e.g. donderdag 16 november 2023 format
    candidate_birth_date: "11 november 1996" # Use e.g. 4 februari 1994
  defense_time: "XX:XX"
  candidate_birthplace: "Trieste, Italy"

  # Supervisors and examiners
  supervisors:
    - title: "Dr."
      name: "Arianna Bisazza"
  cosupervisors:
    - title: "Prof. Dr."
      name: "Malvina Nissim"
    - title: "Dr."
      name: "Grzegorz Chrupa≈Ça"
  committee:
    - title: "Prof. dr."
      name: "XXX XXX"
    - title: "Prof. dr."
      name: "XXX XXX"
    - title: "Prof. dr."
      name: "XXX XXX"

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    template: template/rug-phd-thesis.tex
    pdf-engine: pdflatex
    keep-tex: false


